# Generated by Django 4.2.7 on 2024-12-08 03:51

import cloudinary.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_content_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudinaryFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="file"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="local_files/")),
            ],
        ),
        migrations.AlterField(
            model_name="content",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="media/contents/"
                ),
                upload_to="",
            ),
        ),
    ]
