# Generated by Django 4.2.7 on 2024-12-10 00:29

import ckeditor.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_cloudinaryfile_localfile_alter_content_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\lroja\\Desktop\\github\\proyecto-portal-academico-2024\\Fase 2\\djangoproject\\media"
                ),
                upload_to="",
            ),
        ),
    ]
