# Generated by Django 4.2.7 on 2024-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0003_alter_staff_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="foto",
            field=models.ImageField(blank=True, upload_to="students/fotos/"),
        ),
    ]
