# Generated by Django 4.2.7 on 2024-11-12 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0008_alter_subject_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "target_user_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("teacher", "Profesor"),
                            ("student", "Estudiante"),
                            ("representative", "Representante"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="corecode.subject",
                    ),
                ),
            ],
        ),
    ]
