# Generated by Django 4.2.7 on 2024-11-12 21:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0009_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
