# Generated by Django 4.2.7 on 2024-11-21 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        ("students", "0008_student_subjects"),
        ("corecode", "0010_alter_announcement_content"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="class_record",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="teachers.classrecord",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "class_record")},
        ),
    ]
