# Generated by Django 4.2.7 on 2024-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0007_attendance"),
        ("teachers", "0002_alter_teacher_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="teachers", to="corecode.subject"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="foto",
            field=models.ImageField(blank=True, upload_to="students/fotos/"),
        ),
    ]
