# Generated by Django 4.2.7 on 2024-11-01 02:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0005_usertype"),
        ("students", "0004_student_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="tipo_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corecode.usertype",
                verbose_name="Tipo de Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
