# Generated by Django 4.2.7 on 2024-11-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_tipo_usuario_alter_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="tipo_usuario",
        ),
    ]
