# Generated by Django 4.2.7 on 2024-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0007_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nombre"),
        ),
    ]
