# Generated by Django 4.2.7 on 2024-11-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0004_annotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="annotation",
            name="annotation_type",
            field=models.CharField(
                choices=[("positiva", "Positiva"), ("negativa", "Negativa")],
                max_length=10,
            ),
        ),
    ]
