# Generated by Django 4.2.7 on 2024-11-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("activo", "Activo"), ("cerrado", "Cerrado")],
                default="activo",
                max_length=20,
            ),
        ),
    ]
