# Generated by Django 4.2.7 on 2024-11-14 00:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_student_subjects"),
        ("corecode", "0008_alter_subject_name"),
        ("finance", "0002_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="balance_from_previous_term",
            field=models.IntegerField(
                default=0, verbose_name="Saldo del periodo anterior"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="class_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.studentclass",
                verbose_name="Curso",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.academicsession",
                verbose_name="Año",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("activo", "Activo"), ("cerrado", "Cerrado")],
                default="activo",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
                verbose_name="Estudiante",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="corecode.academicterm",
                verbose_name="Semestre",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="amount",
            field=models.IntegerField(verbose_name="Monto"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(max_length=200, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
                verbose_name="Factura",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="amount_paid",
            field=models.IntegerField(verbose_name="Monto Pagado"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="comment",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Comentario"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="date_paid",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de Pago"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoice",
                verbose_name="Factura",
            ),
        ),
    ]
