# Generated by Django 4.2.7 on 2024-11-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_invoice_balance_from_previous_term_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.invoiceitem",
                verbose_name="Elemento pagado",
            ),
            preserve_default=False,
        ),
    ]
