# Generated by Django 4.2.7 on 2024-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("image_url", models.URLField()),
                ("description", models.TextField()),
            ],
        ),
    ]
