# Generated by Django 3.2.25 on 2024-11-01 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20241031_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Ingrese un correo electrónico válido.', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
