# Generated by Django 4.2.7 on 2024-11-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0007_attendance"),
        ("students", "0007_student_representante"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="corecode.subject"
            ),
        ),
    ]
