"""
Django settings for school_app project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import cloudinary_storage

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "__$1ud47e&nyso5h5o3fwnqu4+hfqcply9h$k*h2s34)hn5@nc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['proyecto-portal-academico-2024.vercel.app', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "widget_tweaks",
    "apps.corecode",
    "apps.students",
    "apps.staffs",
    "apps.finance",
    "apps.result",
    "apps.teachers",
    "apps.representatives",
    "apps.content",
    "apps.isle",
    "ckeditor",
    "ckeditor_uploader",
    "rest_framework",
    'cloudinary',
    'cloudinary_storage'
]

X_FRAME_OPTIONS = "SAMEORIGIN"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.corecode.middleware.SiteWideConfigs",
    "apps.teachers.middleware.TeacherID",
    "apps.students.middleware.StudentID",
    "apps.representatives.middleware.RepresentativesID",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # Here
]

ROOT_URLCONF = "school_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.corecode.context_processors.site_defaults",
            ],
            
            "libraries":{
                "custom_templatetag": 'apps.templatetags.user_groups',
                "student_extras": 'apps.templatetags.student_extras',
                "custom_tags": 'apps.templatetags.custom_tag',
                "representative_tags": 'apps.templatetags.student_tags',
                }
        },
    },
]

WSGI_APPLICATION = "school_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
#    }
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'HOST': "aws-0-us-east-1.pooler.supabase.com",
#        'NAME': "postgres",
#        'USER': "postgres.kmcujloiikbmdrqawwtk",
#        'PASSWORD': "F0vXoNnatZhyiY9Q",
#        'PORT': "6543"
#
#    }
#}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'school_appdb',  # Nombre de la base de datos
#        'USER': 'school_appdb_owner',  # Nombre de usuario
#        'PASSWORD': 'VK0yM3DeHgIq',  # Contraseña
#        'HOST': 'ep-long-sea-a4m2kl2u.us-east-1.aws.neon.tech',  # Host
#        'PORT': '5432',  # Puerto predeterminado de PostgreSQL
#        'OPTIONS': {
#            'sslmode': 'require',  # Activar SSL
#        },
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'school_appdb',
        'USER': 'postgres',
        'PASSWORD': 'asdasd123',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c client_encoding=UTF8'  # Forzar UTF-8
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True   

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_ALLOW_NONIMAGE_FILES = True

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'extraPlugins': ','.join(['image', 'uploadimage']),  # Agregar 'uploadimage' para subir imágenes
        'imageUploadUrl': '/ckeditor/upload/',  # Ruta de subida para imágenes
        'autoParagraph': False,
        'allowedContent': True,  # Permitir todos los tipos de contenido
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

STATIC_URL = "/static/"

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/"

LOGIN_URL = '/accounts/login/'

SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_AGE = 10800

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "lrojaspaila@gmail.com"
EMAIL_HOST_PASSWORD = "lmjc gapy ucye uvbe"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dnoiutiy8',
    'API_KEY': '173315584416318',
    'API_SECRET': 'x0fRVijY5q1mFo8wAvPEhri5Wbk'
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',  # Logs a la consola
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],  # Solo consola
        'level': 'INFO',  
    },
}


DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Site Default values


os.environ.setdefault("DJANGO_SETTINGS_MODULE", "school_app.settings")

WEBPAY_COMMERCE_CODE = "597055555532"
WEBPAY_API_KEY = "tu-api-key-aqui"