# Generated by Django 4.2 on 2024-09-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('primer_nombre', models.CharField(max_length=120)),
                ('segundo_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('primer_apellido', models.CharField(max_length=120)),
                ('segundo_apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('telefono', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
