# Generated by Django 5.1.1 on 2024-09-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('created_ad', models.DateField(auto_now_add=True)),
                ('updated_ad', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('primer_nombre', models.CharField(max_length=120)),
                ('segundo_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('primer_apellido', models.CharField(max_length=120)),
                ('segundo_apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('telefono', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('tipo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AulaVirtual.tipousuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
