# Generated by Django 5.1.1 on 2024-09-30 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AulaVirtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alumnos', models.ManyToManyField(limit_choices_to={'tipo_usuario__tipo': 'Alumno'}, related_name='cursos', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(limit_choices_to={'tipo_usuario__tipo': 'Profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('positiva', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'tipo_usuario__tipo': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(limit_choices_to={'tipo_usuario__tipo': 'Profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AulaVirtual.curso')),
            ],
        ),
    ]
