# Generated by Django 4.2 on 2024-10-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AulaVirtual', '0002_clase_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('created_ad', models.DateField(auto_now_add=True, null=True)),
                ('updated_ad', models.DateField(auto_now=True)),
            ],
        ),
    ]
