# Generated by Django 5.1.1 on 2024-10-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AulaVirtual', '0002_curso_anotacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AulaVirtual.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='recursos/')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AulaVirtual.unidad')),
            ],
        ),
    ]
