# Generated by Django 5.1.1 on 2024-10-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AulaVirtual', '0003_unidad_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(upload_to='media/recursos/'),
        ),
    ]
