# Generated by Django 5.1.1 on 2024-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AulaVirtual', '0004_alter_recurso_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(upload_to='media'),
        ),
    ]
