# Generated by Django 5.1.1 on 2024-10-07 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AulaVirtual', '0006_alter_recurso_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('asignatura', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('comentarios', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='anuncios/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AulaVirtual.curso')),
            ],
        ),
    ]
