# Generated by Django 5.1.1 on 2024-10-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AulaVirtual', '0007_anuncio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
